### PR TITLE
Add hidden and private surveys with access right checking

### PR DESCRIPTION
**Pull request by hguenot**
- Hidden survey : So the survey is not visible while user is creating it
- Private survey : Choose users who can answer to survey
- Access right : user can't see hidden or private survey 
- Make fields disabled when survey is answered 
- Search user is accessible only if `IdentityClass` implements `SurveyInterface`

### CODE REVIEW

**Comment by onmotion** [comment]
Hi!

What we do with the already user assignment existed feature ([respondents.php](https://github.com/onmotion/yii2-survey/blob/master/views/default/respondents.php))?

**Comment by hguenot** [comment]
Hi,

On my understanding, anyone can vote on a survey. And in respondents.php, we can see who has voted and reset the vote status. 
When I click on the red trash, "respondent" disappear, and user can click on "done" again.
Furthermore, there is no restriction anywhere in the code (I add it in this pull request).

My "private" flags is a restriction of who can vote...
Maybe we can merge the two things in one... but I think the "respondent" view will be difficult to understand...

**Comment by onmotion** [comment]
Sounds reasonable. But what if will be added many users (fa 1000). Without pagination, it will slow down the page...

**Comment by hguenot** [comment]
Maybe we raise memory limit before :D Yes of course... I didn't make test load... 
I think if you need to add 1000 users, we need to think another way to restrict the poll (ie restrict to user with a specific access right or allows developer to "inject" their own users filtering class/method)

**Comment by hguenot** [comment]
But I will update to use same method as respondents.

**Comment by onmotion** [comment]
In my case, I do so:
In the users GRID, a have checkboxes which can bulk assign the survey through modal
image

image

And only these users can access to the survey.

**Comment by hguenot** [comment]
Hi, view / user selection adapted as discussed...

**Comment by onmotion** [comment]
Hi. Cool! I check it out tomorrow. 
Thank you!

**Pull request merged**
